[module]
path = "example::explorer"

[dependencies]
"ecosystem::walkdir" = true
"ecosystem::notify" = true
"ecosystem::terminal" = true
"ecosystem::tui" = true
"ecosystem::ansi" = true
"ecosystem::color" = true
"ecosystem::progress" = true
"ecosystem::tui_markdown" = true
"ecosystem::tempfile" = true
